### ISSUE TITLE
Add MacOS runners in CI

### ISSUE THREAD

**Issue by ckormanyos** [ckormanyos/mandelbrot#65]

**Comment by suryaoruganti** [comment]
Hey, if you're looking for fast MacOS runners on apple silicon powered by M2 Pros, you might want to check out WarpBuild. (I'm the founder)

**Comment by ckormanyos** [comment]
>  looking for fast MacOS runners on apple silicon powered by M2 Pros, you might want to check out WarpBuild

Thanks for the suggestion @suryaoruganti I'm missing those runners on GHA. Looks like nice work at your site.

At the moment, I'm old and in the process of commissioning my projects for long-term. But I'll keep your query in mind and pass it along to the colleagues.
